services:
  postgres:
    image: postgres:16-alpine
    container_name: ecorota-db
    environment:
      POSTGRES_USER: ecorota
      POSTGRES_PASSWORD: ecorota
      POSTGRES_DB: ecorota
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: