import { Point, Collector } from '@ecorota/shared';

export const MOCK_POINTS: Point[] = [
  {
    id: 'point-1',
    name: 'Ponto 1 - Praça da Sé',
    kind: 'habitual',
    coordinates: [-46.6333, -23.5505],
    circuit: 1,
    demand: { pending: 2, assigned: 1, in_service: 0, completed: 5, cancelled: 0 },
  },
  {
    id: 'point-2',
    name: 'Ponto 2 - Av. Paulista',
    kind: 'habitual',
    coordinates: [-46.6559, -23.5615],
    circuit: 1,
    demand: { pending: 1, assigned: 0, in_service: 1, completed: 8, cancelled: 0 },
  },
  {
    id: 'point-3',
    name: 'Ponto 3 - Parque Ibirapuera',
    kind: 'habitual',
    coordinates: [-46.6576, -23.5874],
    circuit: 1,
    demand: { pending: 3, assigned: 1, in_service: 0, completed: 12, cancelled: 1 },
  },
  {
    id: 'point-4',
    name: 'Ponto 4 - Vila Madalena',
    kind: 'habitual',
    coordinates: [-46.6908, -23.5552],
    circuit: 1,
    demand: { pending: 0, assigned: 2, in_service: 0, completed: 4, cancelled: 0 },
  },
  {
    id: 'point-5',
    name: 'Ponto 5 - Pinheiros',
    kind: 'habitual',
    coordinates: [-46.6966, -23.5673],
    circuit: 1,
    demand: { pending: 1, assigned: 0, in_service: 0, completed: 7, cancelled: 0 },
  },
  {
    id: 'point-6',
    name: 'Ponto 6 - Faria Lima',
    kind: 'habitual',
    coordinates: [-46.6853, -23.5801],
    circuit: 1,
    demand: { pending: 4, assigned: 1, in_service: 1, completed: 15, cancelled: 2 },
  },
  {
    id: 'point-7',
    name: 'Ponto 7 - Moema',
    kind: 'habitual',
    coordinates: [-46.6644, -23.6027],
    circuit: 2,
    demand: { pending: 0, assigned: 1, in_service: 0, completed: 9, cancelled: 0 },
  },
  {
    id: 'point-8',
    name: 'Ponto 8 - Itaim Bibi',
    kind: 'habitual',
    coordinates: [-46.6781, -23.5847],
    circuit: 2,
    demand: { pending: 2, assigned: 0, in_service: 1, completed: 6, cancelled: 0 },
  },
  {
    id: 'point-9',
    name: 'Ponto 9 - Brooklin',
    kind: 'habitual',
    coordinates: [-46.6912, -23.6121],
    circuit: 2,
    demand: { pending: 1, assigned: 1, in_service: 0, completed: 3, cancelled: 0 },
  },
  {
    id: 'point-10',
    name: 'Ponto 10 - Morumbi',
    kind: 'habitual',
    coordinates: [-46.7135, -23.6001],
    circuit: 2,
    demand: { pending: 0, assigned: 0, in_service: 0, completed: 10, cancelled: 1 },
  },
  {
    id: 'point-11',
    name: 'Ponto 11 - Ponto Adicional A',
    kind: 'additional',
    coordinates: [-46.6412, -23.5651],
    circuit: 2,
    demand: { pending: 5, assigned: 0, in_service: 0, completed: 2, cancelled: 0 },
  },
  {
    id: 'point-12',
    name: 'Ponto 12 - Ponto Adicional B',
    kind: 'additional',
    coordinates: [-46.6715, -23.5489],
    circuit: 2,
    demand: { pending: 2, assigned: 2, in_service: 0, completed: 1, cancelled: 0 },
  },
];

export const MOCK_COLLECTORS: Collector[] = [
  {
    id: 'collector-1',
    name: 'Coletor 01 (Sistema)',
    origin: 'system',
    available: true,
    status: 'moving',
    circuit: 1,
    position: {
      type: 'Point',
      coordinates: [-46.6500, -23.5550],
    },
    observedAt: new Date().toISOString(),
  },
  {
    id: 'collector-2',
    name: 'Coletor 02 (Sistema)',
    origin: 'system',
    available: true,
    status: 'moving',
    circuit: 2,
    position: {
      type: 'Point',
      coordinates: [-46.6800, -23.5950],
    },
    observedAt: new Date().toISOString(),
  },
  {
    id: 'collector-3',
    name: 'Coletor Autônomo João',
    origin: 'custom',
    available: true,
    status: 'idle',
    circuit: 1,
    position: {
      type: 'Point',
      coordinates: [-46.6600, -23.5700],
    },
    observedAt: new Date().toISOString(),
  },
];
